[package]
name = "traveler"
version = "0.1.0"
authors = ["Danny Hadley <dadleyy@gmail.com>"]
edition = "2018"

[[bin]]
name = "traveler"
path = "src/traveler/main.rs"


[[bin]]
name = "queen"
path = "src/queen/main.rs"

[dependencies]
